### ISSUE TITLE
NGINX Reverse proxy 502 BAD GATEWAY

### ISSUE THREAD

**Issue by hzlzh** [pupubird/get-github-trending#1]
I use NGINX Reverse proxy to pull your API like this, but only get `Nginx - Reverse proxy - 502 BAD GATEWAY` error.

`https://apispeedy.com/github-trending-daily/  -> https://hackertab.pupubird.com/repositories?since=daily`

here is the request log `[25/Jan/2021:15:46:25 +0800] "GET / HTTP/2.0" 502 552`
maybe you can check your server access log to see what happened

**Comment by pupubird** [comment]
Hey hey, it seems that you had configured you nginx wrongly

**Comment by pupubird** [comment]
May I have your nginx configuration details, and what are you trying to achieve ?

**Comment by hzlzh** [comment]
```bash
#PROXY-START/
location ~* \.(php|jsp|cgi|asp|aspx)$
{
	proxy_pass https://hackertab.pupubird.com;
    proxy_set_header Host hackertab.pupubird.com;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
}
location /
{
    proxy_pass https://hackertab.pupubird.com;
    proxy_set_header Host hackertab.pupubird.com;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    
    add_header X-Cache $upstream_cache_status;
    
    #Set Nginx Cache
    
    	add_header Cache-Control no-cache;
    expires 12h;
}

#PROXY-END/
```

**Comment by pupubird** [comment]
Did you put your location block under server block?

**Comment by hzlzh** [comment]
try this https://tttt.apispeedy.com/
````bash
#PROXY-START/
location ~* \.(php|jsp|cgi|asp|aspx)$
{
	proxy_pass https://twitter.com;
    proxy_set_header Host twitter.com;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
}
location /
{
    proxy_pass https://twitter.com;
    proxy_set_header Host twitter.com;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    
    add_header X-Cache $upstream_cache_status;
    
    #Set Nginx Cache
    
    	add_header Cache-Control no-cache;
    expires 12h;
}

#PROXY-END/
````

**Comment by hzlzh** [comment]
I found that, only your domain with your server could not be reverse proxy, so weird!

**Comment by pupubird** [comment]
Do notice that https://hackertab.pupubird.com/ itself will return unauthenticated status code, I suppose that's why its showing error on your nginx.

**Comment by hzlzh** [comment]
```
$ curl -i https://hackertab.pupubird.com/
HTTP/2 403
content-type: application/json
content-length: 42
date: Mon, 25 Jan 2021 08:57:09 GMT
x-amzn-requestid: cfa23fba-daa5-4eb8-b82b-50f605ff3fc3
x-amzn-errortype: MissingAuthenticationTokenException
x-amz-apigw-id: ZsorzEJ3yQ0FuMQ=
via: 1.1 824b6b17b59323f523bbeab054eeb246.cloudfront.net (CloudFront), 1.1 c3da0971c4e40021ef7b7d156b3881d6.cloudfront.net (CloudFront)
x-amz-cf-pop: SIN52-C2
x-cache: Error from cloudfront
x-amz-cf-pop: HKG60-C1
x-amz-cf-id: DiypNKBENYngTaFU6XysjOazP8BbPLq9817PindlaG0y6SmY5YQ79A==

{"message":"Missing Authentication Token"}%
```

**Comment by pupubird** [comment]
But nevertheless, the backend is actually hosted on aws lambda + api gateway 😅 there is no "server" that's serving this api.

**Comment by hzlzh** [comment]
how about your firewall?

**Comment by hzlzh** [comment]
can u check the gateway if there is some way to allow request like me, I'd like to use your  API with on of my plugin on macOS

**Comment by pupubird** [comment]
Do check on this https://stackoverflow.com/questions/39591495/nginx-proxy-pass-to-aws-api-gateway

😅 if you would like to, you may host the API with you aws account

Will be closing this issue very soon if there isnt any much problem on the project itself 😎😎

**Comment by hzlzh** [comment]
I prefer to use your API firstly, thanks a lot with your help on this issue.

**Comment by pupubird** [comment]
No worries!
